# -*- coding: utf-8 -*-
"""FirstStream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJ3ByrC_uT74mGx1S_MY0-oTjTvjaJCN
"""

import streamlit as st

st.title('My First StreamLit Project - Testing my Sugarboooooo')
st.write()
