# -*- coding: utf-8 -*-
"""QRCodeGenerate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OaY3DMEDzzpkxLaChd-oVI7GBU54CVW
"""

import pyqrcode
import streamlit as st


def generateQR(text):
    qrText = pyqrcode.create(content = text)
    qrText.svg('QRCode.svg', scale = 19)
    return qrText

print(type(generateQR('Neha V Singh')))

st.title('Text to QR Code Generator')
st.subheader('Convert your text and generate QR Code')

txt = st.text_area(label = 'Enter Text to Generate QR Code: ', value = 'Enter Text Here!')
color = st.color_picker(label = 'Pick a Color')

